### ISSUE TITLE
Improve search engine

### ISSUE THREAD

**Issue by Nadeflore** [Nadeflore/dakara-server#7]
Search songs by matching artists, works, tags

Use mini language to specify search field.
ex:
```
artist:<artist name>
work:<work name> (alternative: <work_type>:<work name>)
title:<song title>
#<tag>
```
Partial matching by default, switch to strict matching with quotes
ex:
```
artist:"<artist name>"
```

Search query without keywords searches in any fields

**Comment by Neraste** [comment]
Maybe use (shlex)[https://pymotw.com/2/shlex/] more intensively.

**Comment by Neraste** [comment]
Alternative work search not implemented.

Done in 2684ade3f52808f65e91c2de439328efbf94d64c 6e608941e717275624367b2e53ad27d3529f0130
ec48cefcd03e33247b4720f6a3a433cebbda8e5a.
